# Generated by Django 5.1.7 on 2025-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_balance_alter_user_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_network',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
